export const LINKS = {
  HOME: "/",
  BLOG: "/blog",
  AUTHORS: "/authors",
  TAGS: "/tags",
  ABOUT: "/contact/about",
  REQUEST: "/contact/request",
  SINGLEPOST: "/single-post",
  POST: "/post",
	PROFILE: '/profile/user',
	AUTHORPROFILE: '/profile/author',
	NEWPOST: '/profile/new-post',
	AUTHSINGIN: '/auth/sing-in',
	AUTHSINGUP: '/auth/sing-up',
} as const;
