export const LINKS = {
	HOME: '/',
	BLOG: '/blog',
	AUTHORS: '/authors',
	TAGS: '/tags',
	ABOUT: '/contact/about',
	REQUEST: '/contact/request',
	SINGLE_POST: '/single-post',
	POST: '/post',
	PROFILE: '/profile/user',
	UPDATE_PROFILE: '/profile/update-profile',
	AUTHOR_PROFILE: '/profile/author',
	NEW_POST: '/profile/new-post',
	UPDATE_POST: '/profile/update-post',
	AUTH_SING_IN: '/auth/sign-in',
	AUTH_SING_UP: '/auth/sign-up',
	AUTHOR_ID: '/author/',
	ADMIN_USERS: '/admin/users',
	ADMIN_POSTS: '/admin/posts',
	ADMIN_OTHER: '/admin/other'
} as const
